# Generated by Django 4.1.3 on 2022-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_votes_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_votes',
            name='v_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_votes',
            name='v_Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
