# Generated by Django 4.1.3 on 2022-11-08 14:25

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish_votes',
            fields=[
                ('dish_Id', models.AutoField(primary_key=True, serialize=False)),
                ('d_Name', models.CharField(max_length=100)),
                ('v_Date', models.DateField()),
            ],
            options={
                'db_table': 'dish_votes',
            },
        ),
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('dish_Id', models.AutoField(primary_key=True, serialize=False)),
                ('d_Name', models.CharField(max_length=100)),
                ('d_Description', models.CharField(max_length=1000)),
                ('d_Ingredients', models.CharField(max_length=500)),
                ('d_Photo', models.FileField(null=True, upload_to=dishes.models.user_directory_path, verbose_name='')),
                ('d_Type', models.CharField(max_length=10)),
                ('d_Add_Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
