# Generated by Django 4.1.3 on 2022-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='d_Photo',
            field=models.FileField(default=1, upload_to='media/fooditems/'),
            preserve_default=False,
        ),
    ]
