# Generated by Django 4.1.3 on 2022-11-08 16:52

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dishes_d_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='d_Photo',
            field=models.FileField(null=True, upload_to=dishes.models.user_directory_path, verbose_name=''),
        ),
    ]
