# Generated by Django 4.1.3 on 2022-11-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishes_d_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_votes',
            name='d_Votes',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
