# Generated by Django 4.1.3 on 2022-11-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dish_votes_d_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_votes',
            name='v_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
