# Generated by Django 4.1.3 on 2022-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dish_votes_v_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='d_Price',
            field=models.IntegerField(max_length=10000, null=True),
        ),
    ]
