# Generated by Django 4.1.3 on 2022-11-15 03:37

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_dishes_d_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='d_Photo',
            field=models.FileField(default=25, upload_to=dishes.models.user_directory_path, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishes',
            name='d_Price',
            field=models.IntegerField(default=25, max_length=500),
            preserve_default=False,
        ),
    ]
