# Generated by Django 4.1.3 on 2022-11-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_dishes_d_photo_alter_dishes_d_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_votes',
            name='d_Votes',
            field=models.IntegerField(default=0, max_length=10000),
        ),
    ]
