# Generated by Django 4.1.3 on 2022-11-16 10:01

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_alter_dish_votes_d_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_votes',
            name='d_Description',
            field=models.CharField(default='d', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish_votes',
            name='d_Ingredients',
            field=models.CharField(default='d', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish_votes',
            name='d_Photo',
            field=models.FileField(default='p', upload_to=dishes.models.user_directory_path, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish_votes',
            name='d_Price',
            field=models.IntegerField(default=70, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish_votes',
            name='d_Type',
            field=models.CharField(default='Veg', max_length=10),
            preserve_default=False,
        ),
    ]
