# Generated by Django 4.1.3 on 2022-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_dish_votes_d_description_dish_votes_d_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_votes',
            name='d_Price',
            field=models.IntegerField(blank=True, max_length=500),
        ),
    ]
